---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: malston/k8s-mgmt
    tag: 0.0.2

inputs:
  - name: config-repo
  - name: repo
  - name: pks-config

run:
  path: repo/tasks/network-profile-mgmt/task.sh
