---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: malston/pks-control-plane
    tag: 0.0.1

inputs:
  - name: config-repo
  - name: repo
  - name: pks-config

run:
  path: repo/tasks/network-profile-mgmt/task.sh
