resources:
- name: config-repo
  type: git
  source:
    uri: ((config-repo.uri))
    branch: master
    private_key: ((config-repo.private_key))

- name: k8s-mgmt-pipeline
  type: git
  source:
    uri: ((k8s-mgmt-pipeline.uri))
    branch: master
    private_key: ((k8s-mgmt-pipeline.private_key))

jobs:
- name: cluster-management
  serial: true
  serial_groups: [k8s-mgmt]
  plan:
  - get: config-repo
    # trigger: true
  - get: repo
    resource: k8s-mgmt-pipeline

  - task: login
    file: repo/tasks/pks-login/task.yml
    params:
      PKS_API_URL: ((pks_api_url))
      PKS_USER: ((pks_user))
      PKS_PASSWORD: ((pks_password))
      CLUSTER_NAME: ((cluster_name))

  - task: manage-cluster
    file: repo/tasks/cluster-mgmt/task.yml
    params:
      PKS_PASSWORD: ((pks_password))
      DELETE_FLAG: true

- name: namespace-management
  serial: true
  serial_groups: [k8s-mgmt]
  plan:
  - get: config-repo
    passed: [cluster-management]
  - get: repo
    resource: k8s-mgmt-pipeline

  - task: login
    file: repo/tasks/pks-login/task.yml
    params:
      PKS_API_URL: ((pks_api_url))
      PKS_USER: ((pks_user))
      PKS_PASSWORD: ((pks_password))
      CLUSTER_NAME: ((cluster_name))

  - task: manage-namespace
    file: repo/tasks/namespace-mgmt/task.yml
    params:
      PKS_PASSWORD: ((pks_password))
      DELETE_FLAG: false

- name: role-management
  serial: true
  serial_groups: [k8s-mgmt]
  plan:
  - get: config-repo
    passed: [namespace-management]
  - get: repo
    resource: k8s-mgmt-pipeline

  - task: login
    file: repo/tasks/pks-login/task.yml
    params:
      PKS_API_URL: ((pks_api_url))
      PKS_USER: ((pks_user))
      PKS_PASSWORD: ((pks_password))
      CLUSTER_NAME: ((cluster_name))

  - task: manage-role
    file: repo/tasks/role-mgmt/task.yml
    params:
      PKS_PASSWORD: ((pks_password))

- name: ingress-management
  serial: true
  serial_groups: [k8s-mgmt]
  plan:
  - get: config-repo
    passed: [namespace-management]
  - get: repo
    resource: k8s-mgmt-pipeline

  - task: login
    file: repo/tasks/pks-login/task.yml
    params:
      PKS_API_URL: ((pks_api_url))
      PKS_USER: ((pks_user))
      PKS_PASSWORD: ((pks_password))
      CLUSTER_NAME: ((cluster_name))

  - task: manage-ingress
    file: repo/tasks/ingress-mgmt/task.yml
    params:
      PKS_PASSWORD: ((pks_password))
