---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: malston/k8s-mgmt
    tag: 0.0.2

inputs:
  - name: config-repo
  - name: repo
  - name: pks-config

params:
  PKS_PASSWORD:
  DELETE_FLAG:

run:
  path: repo/tasks/namespace-mgmt/task.sh
