---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: malston/pks-control-plane
    tag: 0.0.1

inputs:
  - name: config-repo
  - name: repo

params:
  PKS_PASSWORD:
  DELETE_FLAG:

run:
  path: repo/tasks/namespace-mgmt/task.sh
