---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: malston/pks-control-plane
    tag: 0.0.1

inputs:
  - name: repo

outputs:
- name: pks-config
- name: kube-config

params:
  PKS_API_URL:
  PKS_USER:
  PKS_PASSWORD:
  CLUSTER_NAME:

run:
  path: repo/tasks/pks-login/task.sh
