---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: malston/k8s-mgmt
    tag: 0.0.2

inputs:
  - name: repo

outputs:
- name: pks-config
- name: kube-config

params:
  PKS_API_URL:
  PKS_USER:
  PKS_PASSWORD:
  CLUSTER:

run:
  path: repo/tasks/login-pks/task.sh
